/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package medium.nested_list_weighted_sum_339;

import java.util.Arrays;
import java.util.List;

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {
		NestedInteger n1 = new NestedInteger(1, null);
		NestedInteger n2 = new NestedInteger(4, null);
		NestedInteger n3 = new NestedInteger(6, null);
		//NestedInteger n4 = new NestedInteger(1, null);
		//NestedInteger n5 = new NestedInteger(1, null);
		List<NestedInteger> list1 = Arrays.asList(n2);
		List<NestedInteger> list2 = Arrays.asList(n3);
		NestedInteger nested1 = new NestedInteger("", list1);
		NestedInteger nested2 = new NestedInteger("", list2);
		NestedInteger nested3 = new NestedInteger("", Arrays.asList(nested2));

		int cal = cal(Arrays.asList(n1, nested1, nested3));
		System.out.println(cal);
		String s = "";
		for(int i=0;i<s.length();i++) {
			 char c = s.charAt(i);
           System.out.println(c);
		}
	}

	private static int cal(List<NestedInteger> asList) {
		int depth = 1;
		return getDepth(asList, depth);
	}

	private static int getDepth(List<NestedInteger> asList, int depth) {
		int total = 0;
		for (NestedInteger n : asList) {
			if (n.isInt()) {
				System.out.println(n.getInt() + " @ depth "+ depth);
				 total += depth * n.getInt();
			} else {
				total += getDepth(n.getList(),depth + 1);
			}
		}
		return total;
	}
}
